### ISSUE TITLE
HIPSPARSE_STATUS_INVALID_VALUE from hipsparseSpSM_bufferSize

### ISSUE THREAD

**Issue by jinz2014** [ROCm/hipSPARSE#389]
I migrated a CUDA program that executes the cusparseSpSM function.  The HIP program reports the following error for the given command-line options. I am not sure if the error is caused by the library. Thank you for taking a look at the program.

To reproduce:

cd into the directory "spsm-hip" in https://github.com/zjin-lcf/HeCBench/tree/master/spsm-hip
make
./main 4 2 9 1 1
hipSPARSE error: HIPSPARSE API failed at line 224 with error: HIPSPARSE_STATUS_INVALID_VALUE

**Comment by jsandham** [comment]
@jinz2014 Thanks for bringing this to our attention. Ill take a look and get back to you.

**Comment by jsandham** [comment]
@jinz2014 What version of rocsparse are you using for a backend?

**Comment by jinz2014** [comment]
5.4.0 and 5.6.0  from 'cat /opt/rocm/include/rocsparse-version.h'. I ran the program on AMD GPUs.

**Comment by jsandham** [comment]
@jinz2014 Looks like in rocsparse we currently only support column order for the dense matrices. Ill create a ticket to add row ordering so we can match cusparse functionality. Thanks for uncovering this missing functionality.

**Comment by jinz2014** [comment]
Thanks

**Comment by jsandham** [comment]
I have added the previously missing row order functionality to SpSM so this should now be fixed starting in the upcoming 6.2 release. The fix also exists in the develop branch in case you want to verify now instead of waiting for 6.2. The link to your reproducer no longer works for me.  If you find an issue with your reproducer when using develop branch or after the 6.2 release please let me know. Otherwise Ill close for now.

**Comment by jinz2014** [comment]
Ok. Sorry about the link that no longer works. Thanks.
